### ISSUE TITLE
Key in the btree becomes undefined

### ISSUE THREAD

**Issue by CharlesKuncheria** [qwertie/btree-typescript#1]
Is it possible that, when we loop and delete multiple entries from btree, some of the entries/keys in the tree becomes undefined?
Our config: we have entries around 1800, and the base was chosen as 10.
Is this to do with how the balancing logic works?

**Comment by qwertie** [comment]
Can you provide a code sample that demonstrates the problem?

**Comment by qwertie** [comment]
Closed due to lack of information.
