### ISSUE TITLE
Thread safety iterable ?

### ISSUE THREAD

**Issue by ash0080** [qwertie/btree-typescript#11]
Hi, this lib is awesome, thanks for your sharing.
but I had a little problem when I wanted to extend a .next() method to loop through the entire tree

```
this._cursor = undefined
...

BTree.prototype.nextCyclePair = function () {
    var key = this._compare(this._cursor, this.maxKey()) >= 0 ? undefined : this._cursor
    var it  = this.entries(key, ReusedArray)
    var r   = it.next()
    if (!r.done && key !== undefined && this._compare(r.value[0], key) <= 0) {
      r = it.next()
    }
    this._cursor = r.value ? r.value[0] : r.value
    return r.value
  }

```

It works, but unfortunately,  not threads safety, 
if I call async functions in parallel , 
There is a probability that get the same result,

I think it's because **.entries()** returns a new iterator each time, 
so **it.next()** could possible return a same pair
That's why this._cursor not work,

so, my question is 
Is there a way to implement a thread-safe iterator?

Here's a quick & dirty implementation I wrote, base on Map 

```
module.exports = class CycledMap extends Map {
  constructor (...args) {
    super(...args)
    this._indexArr = this.setIndexArr()
    this._index    = 0
  }

  get index () {
    return this._index >= this.size ? 0 : this._index
  }

  set index (index) {
    this._index = index
  }

  getkey (index) {
    return this._indexArr[index]
  }

  next () {
    const key = this.getkey(this.index++)
    return { [key]: this.get(key) }
  }

  setIndexArr () {
    this._indexArr = [...this.keys()]
  }

  clear () {
    super.clear()
    this._index = []
  }

  delete (key) {
    super.delete(key)
    this.setIndexArr()
  }

  set (...args) {
    super.set(...args)
    this.setIndexArr()
  }
}
```

**Comment by qwertie** [comment]
JavaScript does not support multiple threads, so the B+tree is not, and does not need to be, designed for thread safety. 

The `.next()` method returned by the `.entries` method is not designed to work correctly if the tree is modified between calls to `.next`, but that doesn't seem to be the problem here.

I don't know what you want to accomplish with `CycledMap`. If you are saying that you want to "cycle through" the tree in two locations simultaneously, you will need to store the state of each cycle in a separate object.

**Comment by ash0080** [comment]
In short, I want to have a next method that iterates through the numbers and supports atomic operation.
ex.  await Promise.all([x.next(), x.next()])  =>. get two different data

**Comment by qwertie** [comment]
I still don't understand what you're asking for. If there are Promises in the BTree, you can iterate over them, of course.
