### ISSUE TITLE
BTree was not exported

### ISSUE THREAD

**Issue by ebewley** [qwertie/btree-typescript#3]
Tried to use your btree implementation today, but when importing as you stated, it returns an error that there is no exported member BTree.  There is an EmptyBTree, but that isn't usable.  The only things exported, according to intellisense, are the interfaces.

**Comment by qwertie** [comment]
BTree is the default export, so if you do something like `import * as B from 'sorted-btree'`, you won't see it. If I remember right, after you do `npm install sorted-btree`, you can import like this:

    import BTree from "sorted-btree";
