### ISSUE TITLE
Q: find() method

### ISSUE THREAD

**Issue by stacew** [qwertie/btree-typescript#40]
Hello, thank you for providing high quality source code.

Q1. Is the reason why there is no 'find() method' only for 'Map Interface' compatibility?

Q2. Should I use 'values() iterable' instead?

**Comment by qwertie** [comment]
I guess it just didn't occur to me to write a `find` method. Instead you can use `values()`, `entries()`, `forEach()` or `forEachPair()`.

**Comment by stacew** [comment]
Thank you for your answer.
